# -*- coding: utf-8 -*-
"""Jogo Da Forca3B Nathan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRRrIC7MTfKLMAlm5HhZYnv94wxZW0GX
"""

# ============================================================
# JOGO DA FORCA - ADICIONADO A OPÇÃO DE REINICIAR
# Disciplina: Programação no Desenvolvimento de Sistemas
# Turma: 3º Ano do Ensino Médio Técnico
# ============================================================

import random

# Lista única de palavras
palavras = [
    "python", "programacao", "sistema", "algoritmo", "teclado",
    "internet", "computador", "desenvolvedor", "software", "terminal",
    "matematica", "prova", "caderno", "professor", "aluno", "quadro",
    "recreio", "biblioteca", "minecraft", "zelda", "mario", "pokemon",
    "fortnite", "roblox", "avatar", "interestelar", "batman", "matrix"
]

def escolher_palavra():
    """Escolhe uma palavra aleatória da lista."""
    return random.choice(palavras)

def mostrar_palavra(palavra, letras_acertadas):
    """Mostra a palavra com as letras já acertadas."""
    resultado = ""
    for letra in palavra:
        if letra in letras_acertadas:
            resultado += letra + " "
        else:
            resultado += "_ "
    return resultado

def jogar():
    print("=" * 40)
    print("        JOGO DA FORCA - PYTHON")
    print("=" * 40)

    # Loop principal para permitir jogar várias vezes
    while True:
        palavra_secreta = escolher_palavra()
        letras_acertadas = []
        letras_tentadas = []
        vidas = 6
        pontos = 0

        print("\n Descubra a palavra secreta!")
        print(f" Você tem {vidas} vidas.")
        print()

        while vidas > 0:
            print("Palavra:", mostrar_palavra(palavra_secreta, letras_acertadas))
            print("Letras tentadas:", letras_tentadas)
            print(f"Vidas: {vidas} | Pontos: {pontos}")
            print("-" * 40)

            letra = input("Digite uma letra: ").lower().strip()

            # Validação da entrada
            if len(letra) != 1 or not letra.isalpha():
                print("Digite apenas UMA letra válida (A-Z).")
                print()
                continue

            if letra in letras_tentadas:
                print("Você já tentou essa letra.")
                print()
                continue

            letras_tentadas.append(letra)

            if letra in palavra_secreta:
                print("A letra existe na palavra.")
                letras_acertadas.append(letra)
                pontos += 10
            else:
                print("Essa letra não está na palavra.")
                vidas -= 1
                pontos -= 2

            print()

            # Verifica se o jogador venceu
            if all(l in letras_acertadas for l in palavra_secreta):
                print("=" * 40)
                print("PARABÉNS! VOCÊ VENCEU!")
                print(f"A palavra era: {palavra_secreta}")
                print(f"Pontuação final: {pontos}")
                print("=" * 40)
                break

        if vidas == 0:
            print("=" * 40)
            print("FIM DE JOGO!")
            print(f"A palavra era: {palavra_secreta}")
            print(f"Pontuação final: {pontos}")
            print("=" * 40)

        # Pergunta se deseja jogar novamente
        while True:
            resp = input("\nDeseja jogar novamente? (s/n): ").lower().strip()
            if resp in ['s', 'n']:
                break
            print("Digite 's' para sim ou 'n' para não.")

        if resp == 'n':
            print("Obrigado por jogar!")
            break

# Início seguro do programa
if __name__ == "__main__":
    jogar()